trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  solutions: '*.sln'
  build-platform: 'Any-Cpu'
  buildConfiguration: 'Release'
  
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Only a test file
- task: Docker@2
  inputs:
    containerRegistry: 'acrapidiolab02'
    repository: 'apidiolab02'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
# 